########################################################################
########################################################################
##
##    Docker Compose File: SWAG (LinuxServer.io)
##    Function: Reverse proxy with built-in ACME compliant Certbot, for
##    Let's Encrypt / ZeroSSL, and MFA / 2FA authentication mechanisms.
##
##    Documentation: https://docs.linuxserver.io/general/swag
##    https://www.linuxserver.io/blog/zero-trust-hosting-and-reverse-proxy-via-cloudflare-swag-and-authelia
##
########################################################################
########################################################################
version: "3.7"

services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/swag:/config
    ports:
# Set your Internet gateway to forward REVERSE_PROXY_PORT_HTTP(s) ports
# to your internal Docker host IP address. Update in ENV file and redeploy.
      - ${REVERSE_PROXY_PORT_HTTP:?err}:80      # Auto redirects to 443
      - ${REVERSE_PROXY_PORT_HTTPS:?err}:443
    restart: unless-stopped
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - URL=homelan.au
      - SUBDOMAINS=www,
      - VALIDATION=http
      - CERTPROVIDER=                # Optional
      - DNSPLUGIN=cloudflare         # Optional
      - DUCKDNSTOKEN=<token>         # Optional
      - EMAIL=<e-mail>               # Optional
      - ONLY_SUBDOMAINS=false        # Optional
      - EXTRA_DOMAINS=<extradomains> # Optional
      - STAGING=false                # Optional

# This container must not use VPN connection, otherwise reverse proxy functions will not
# work, as ports need to be forwarded from your gateway device, to the Docker host IP address.
networks:
  default:
    name: media_network
    external: true
