########################################################################
########################################################################
##
##  Docker Compose File: Tdarr V2 (haveagitgat/tdarr)
##  Function: Tdarr V2 - Audio/Video library transcoding automation
##            (Contains Tdarr_Server and WebUI ) 
##
##  Documentation: https://docs.tdarr.io/docs/installation/docker/run-compose/
##  https://docs.tdarr.io/docs/installation/docker/hardware-transcoding
##
########################################################################
########################################################################
version: "3.7"

services:
  tdarr:
    image: ghcr.io/haveagitgat/tdarr:latest
    container_name: tdarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/tdarr/server:/app/server
      - ${FOLDER_FOR_DOCKER_DATA:?err}/tdarr/configs:/app/configs
      - ${FOLDER_FOR_DOCKER_DATA:?err}/tdarr/logs:/app/logs
      - ${FOLDER_FOR_MEDIA:?err}/tdarr_transcode_cache:/temp
      - ${FOLDER_FOR_MEDIA:?err}:/data/media
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - serverIP=0.0.0.0
      - serverPort=${TDARR_SERVER_PORT:?err}
      - webUIPort=${WEBUI_PORT_TDARR:?err}
      - internalNode=true
      - nodeID=Tdarr_Server
# Configure VPN / Direct Internet access below. You will also need to make change in the Gluetun VPN Container

    network_mode: "container:gluetun"                        ## Disable to bypass Gluetun VPN for Internet traffic
#    ports:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#      - "${TDARR_SERVER_PORT:?err}:${TDARR_SERVER_PORT:?err}"    # Tdarr: Server Port     ## Enable  to bypass Gluetun VPN for Internet traffic
#      - "${WEBUI_PORT_TDARR:?err}:${WEBUI_PORT_TDARR:?err}"      # Tdarr: WebUI Portal    ## Enable  to bypass Gluetun VPN for Internet traffic



  tdarr-node:
    image: ghcr.io/haveagitgat/tdarr_node:latest
    container_name: tdarr-node
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/tdarr/configs:/app/configs
      - ${FOLDER_FOR_DOCKER_DATA:?err}/tdarr/logs:/app/logs
      - ${FOLDER_FOR_MEDIA:?err}/transcode_cache:/temp
      - ${FOLDER_FOR_MEDIA:?err}:/data/media
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
      - nodeID=Tdarr_Node_1
      - serverIP=0.0.0.0
      - serverPort=${TDARR_SERVER_PORT:?err}
# Configure VPN / Direct Internet access below. You will also need to make change in the Gluetun VPN Container

    network_mode: "container:gluetun"                        ## Disable to bypass Gluetun VPN for Internet traffic
#networks:                                                   ## Enable  to bypass Gluetun VPN for Internet traffic
#  default:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#    name: media_network                                     ## Enable  to bypass Gluetun VPN for Internet traffic
#    external: true                                          ## Enable  to bypass Gluetun VPN for Internet traffic
