########################################################################
########################################################################
##
##  Docker Compose File: Sonarr (LinuxServer.io)
##  Function: Series Library Manager (TV Shows)
##
##  Documentation: https://docs.linuxserver.io/images/docker-sonarr
##
########################################################################
########################################################################
version: "3.7"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/sonarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${TP_THEME:?err}

# Configure VPN / Direct Internet access below. You will also need to make change in the Gluetun VPN Container

    network_mode: "container:gluetun"                        ## Disable to bypass Gluetun VPN for Internet traffic
#    ports:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#      - "${WEBUI_PORT_SONARR:?err}:8989"                    ## Enable  to bypass Gluetun VPN for Internet traffic
#networks:                                                   ## Enable  to bypass Gluetun VPN for Internet traffic
#  default:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#    name: media-network                                     ## Enable  to bypass Gluetun VPN for Internet traffic
#    external: true                                          ## Enable  to bypass Gluetun VPN for Internet traffic
