########################################################################
########################################################################
##
##  Docker Compose File: Lidarr (LinuxServer.io)
##  Function: Music Library Manager
##
##  Documentation: https://docs.linuxserver.io/images/docker-lidarr
##
########################################################################
########################################################################
version: "3.7"

services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/lidarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=${TP_THEME:?err}

# Configure VPN / Direct Internet access below. You will also need to make change in the Gluetun VPN Container

    network_mode: "container:gluetun"                        ## Disable to bypass Gluetun VPN for Internet traffic
#    ports:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#      - "${WEBUI_PORT_LIDARR:?err}:8686"                    ## Enable  to bypass Gluetun VPN for Internet traffic
#networks:                                                   ## Enable  to bypass Gluetun VPN for Internet traffic
#  default:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#    name: media-network                                     ## Enable  to bypass Gluetun VPN for Internet traffic
#    external: true                                          ## Enable  to bypass Gluetun VPN for Internet traffic
