########################################################################
########################################################################
##
##    Docker Compose File: Authelia (Authelia)
##    Function: Multi-factor authentication portal for your Apps
##
##    Documentation: https://hub.docker.com/r/authelia/authelia
##    https://www.authelia.com/integration/prologue/get-started/
##    https://www.linuxserver.io/blog/zero-trust-hosting-and-reverse-proxy-via-cloudflare-swag-and-authelia
##
########################################################################
########################################################################
version: "3.7"

  authelia:
    image: ghcr.io/authelia/authelia:latest
    container_name: authelia
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/authelia:/config
    restart: unless-stopped

networks:
  default:
    name: media-network
    external: true
