########################################################################
########################################################################
##
##  Docker Compose File: Flaresolverr (Flaresolverr)
##  Function: Cloudflare Proxy Server
##
##  Documentation: https://github.com/FlareSolverr/FlareSolverr
##
########################################################################
########################################################################
version: "3.7"

services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    ports:                                      ## Enable  to bypass Gluetun VPN for Internet traffic
      - "${FLARESOLVERR_PORT:?err}:8191"  ## Enable  to bypass Gluetun VPN for Internet traffic
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TIMEZONE:?err}

#    network_mode: "container:gluetun"            ## Disable to bypass Gluetun VPN for Internet traffic

networks:
  default:
    name: media-network
    external: true