########################################################################
########################################################################
##
##  Docker Compose File: Readarr (LinuxServer.io)
##  Function: Book Library Manager
##
##  Documentation: https://docs.linuxserver.io/images/docker-readarr
##
########################################################################
########################################################################
version: "3.7"

services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    restart: unless-stopped
    volumes:
      - ${FOLDER_FOR_DOCKER_DATA:?err}/readarr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data/media
      - ${FOLDER_FOR_TORRENTS:?err}:/data/torrents
      - ${FOLDER_FOR_USENET:?err}:/data/usenet
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - TZ=${TIMEZONE:?err}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:readarr
      - TP_THEME=${TP_THEME:?err}

# Configure VPN / Direct Internet access below. You will also need to make change in the Gluetun VPN Container

    network_mode: "container:gluetun"                        ## Disable to bypass Gluetun VPN for Internet traffic
#    ports:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#      - "${WEBUI_PORT_READARR:?err}:8787"                   ## Enable  to bypass Gluetun VPN for Internet traffic
#networks:                                                   ## Enable  to bypass Gluetun VPN for Internet traffic
#  default:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#    name: media_network                                     ## Enable  to bypass Gluetun VPN for Internet traffic
#    external: true                                          ## Enable  to bypass Gluetun VPN for Internet traffic
