########################################################################
########################################################################
##
##  Docker Compose File: Whisparr (Hotio.Dev)
##  Function: Adult Media Library Manager
##
##  Documentation: https://wiki.servarr.com/whisparr
##
########################################################################
########################################################################
version: "3.7"

services:
  whisparr:
    image: hotio/whisparr:nightly
    container_name: whisparr
    volumes:
      - ${FOLDER_FOR_CONFIGS:?err}/whisparr:/config
      - ${FOLDER_FOR_MEDIA:?err}:/data
    environment:
      - PUID=${PUID:?err}
      - PGID=${PGID:?err}
      - UMASK=${UMASK:?err}
      - TZ=${TIMEZONE:?err}

# Configure VPN / Direct Internet access below. You will also need to make change in the Gluetun VPN Container

    network_mode: "container:gluetun"                        ## Disable to bypass Gluetun VPN for Internet traffic
#    ports:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#      - "${WEBUI_PORT_WHISPARR:?err}:6969"                  ## Enable  to bypass Gluetun VPN for Internet traffic
#networks:                                                   ## Enable  to bypass Gluetun VPN for Internet traffic
#  default:                                                  ## Enable  to bypass Gluetun VPN for Internet traffic
#    name: media-network                                     ## Enable  to bypass Gluetun VPN for Internet traffic
#    external: true                                          ## Enable  to bypass Gluetun VPN for Internet traffic